module.exports = {
  apps: [
    {
      name: "hermes-api",
      cwd: process.cwd(),
      script: "node",
      args: "scripts/run-node-with-root-env.mjs apps/api/dist/index.js",
      env: {
        NODE_ENV: "production",
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      max_memory_restart: "512M",
      time: true,
    },
    {
      name: "hermes-indexer",
      cwd: process.cwd(),
      script: "node",
      args: "scripts/run-node-with-root-env.mjs packages/chain/dist/indexer.js",
      env: {
        NODE_ENV: "production",
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      max_memory_restart: "256M",
      time: true,
    },
    {
      name: "hermes-worker",
      cwd: process.cwd(),
      script: "node",
      args: "scripts/run-node-with-root-env.mjs apps/api/dist/worker.js",
      env: {
        NODE_ENV: "production",
      },
      autorestart: true,
      max_restarts: 10,
      exp_backoff_restart_delay: 3000,
      max_memory_restart: "512M",
      time: true,
    },
    {
      name: "hermes-mcp",
      cwd: process.cwd(),
      script: "node",
      args: "scripts/run-node-with-root-env.mjs apps/mcp-server/dist/index.js",
      env: {
        NODE_ENV: "production",
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      max_memory_restart: "256M",
      time: true,
    },
  ],
};
