ALTER TABLE submissions
  ADD COLUMN IF NOT EXISTS result_format text NOT NULL DEFAULT 'plain_v0';

ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE proof_bundles ENABLE ROW LEVEL SECURITY;
ALTER TABLE verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE score_jobs ENABLE ROW LEVEL SECURITY;
